import React, { useState, useEffect } from 'react';
import { db } from '../firebase'; // Import the db object from firebase.js
import { useParams, useNavigate } from 'react-router-dom'; // Import useNavigate hook
import styled from 'styled-components';
import FoodBack from '../images/foodBacker.jpeg'
import { collection, doc, getDocs, addDoc, updateDoc, deleteDoc, getDoc } from "firebase/firestore"; 
import { Modal,Spin,Row,Col,Form, Input, Button } from 'antd';
import {BsFillArrowLeftCircleFill} from 'react-icons/bs';




const Grubs = () => {
  const [cityData, setCityData] = useState(null);
  const [grubsData, setGrubsData] = useState([]); 
  const [isModalOpen, setIsModalOpen] = useState(false);
  const { id: cityId } = useParams();
  const navigate = useNavigate();

  const handleGoBack = () => {
    navigate(-1);
  };

  const getForCityGrubs = async () => {
    try {
      const grubsSnapshot = await getDocs(collection(db, "grubs"));
      const grubsData = grubsSnapshot.docs.map(doc => doc.data());
      setGrubsData(grubsData.filter(grub => grub.cityId === cityData.id)); // Filter grubs based on city.id
    } catch (error) {
      console.error("Error getting grubs data:", error);
    }
  }

  const getCityData = async () => {
    try {
      if (cityId) {
        const cityDocRef = doc(db, 'cities', cityId);
        const cityDocSnapshot = await getDoc(cityDocRef);
        if (cityDocSnapshot.exists()) {
          setCityData(cityDocSnapshot.data());
        } else {
          console.log(`City with ID '${cityId}' not found in Firebase`);
        }
      }
    } catch (error) {
      console.error('Error fetching city data from Firebase: ', error);
    }
  };

  const createGrub = async (name, ambience, grub, service, type) => {
    try {
      const newGrub = {
        id: '', // Leave the ID empty to be generated by Firebase
        cityId: cityData.id, // Set the cityId to cityData.id
        name: name,
        ambience: ambience,
        grub: grub,
        service: service,
        type: type,
        total: (ambience + grub + service) / 3 // Calculate average score
      };

      // Add the new grub to Firebase
      const grubDocRef = await addDoc(collection(db, 'grubs'), newGrub);
      newGrub.id = grubDocRef.id; // Set the generated ID to newGrub.id
      setGrubsData([...grubsData, newGrub]); // Add the new grub to local state
    } catch (error) {
      console.error('Error creating new grub:', error);
    }
  };

  // Function to handle form submission for creating a new grub
  const handleCreateGrub = async (event) => {
    event.preventDefault();
    const { name, ambience, grub, service, type } = event.target;
    createGrub(name.value, parseFloat(ambience.value), parseFloat(grub.value), parseFloat(service.value), type.value);
    event.target.reset();
  };


  useEffect(() => {
    getCityData();
  }, [cityId]);

  useEffect(() => {
    if (cityData) {
      getForCityGrubs(); // Fetch grubs data after cityData is set
    }
  }, [cityData]);

  const showModal = () => {
    setIsModalOpen(true);
  };

  const handleOk = () => {
    setIsModalOpen(false);
  };

  const handleCancel = () => {
    setIsModalOpen(false);
  };

  return (
    <Container>
      <ContentContainer>
        {cityData ? (
          <>
            <BackButton onClick={handleGoBack}><BsFillArrowLeftCircleFill/></BackButton>
            <HeaderCity>
              <HeaderTop>
                {cityData.name}
              </HeaderTop>
              <HeaderBottom>
                {cityData.state}
              </HeaderBottom>
            </HeaderCity>
            <AddGrubButton onClick={showModal}>+</AddGrubButton>
            <Modal open={isModalOpen} onOk={handleOk} onCancel={handleCancel}
            footer={[
                <button>
                  Submit
                </button>,
              ]}
            >
            <Form>
              <Form.Item name="grub" label="Grub" rules={[{ required: true }]}>
                <Input type="number" />
              </Form.Item>
              <Form.Item name="service" label="Service" rules={[{ required: true }]}>
                <Input type="number" />
              </Form.Item>
              <Form.Item name="ambience" label="Ambience" rules={[{ required: true }]}>
                <Input type="number" />
              </Form.Item>
              <Form.Item>
              </Form.Item>
            </Form>
            </Modal>
            {grubsData.map(grub => (
              <GrubContainer key={grub.id}>
                <Row gutter={[8, 8]} justify="center" align="middle">
                  <Col span={21}>
                    {grub.name}
                    <br/>
                    {grub.type}
                  </Col>
                  <Col span={3}>
                    {grub.total}
                  </Col>
                </Row>
              </GrubContainer>
            ))}
          </>
        ) : (
          <Spin  justify="center" align="middle"/>
        )}
      </ContentContainer>
    </Container>
  );
};

const Container = styled.div`
  background-image: url(${FoodBack});
  background-position: center;
  background-size: contain;
  padding-top:10px;
  padding-bottom:10px;
  height:100vh;
`

const ContentContainer = styled.div`
  background: #ffffff;
  margin: 5%;
  padding: 5%;
  border-radius: 15px;
  background-position: center;
  background-size: contain;
  box-shadow: 0 5px 15px rgba(0, 0, 0, 0.2);
  position: relative; /* Add position relative to make back button absolute relative to this container */
`;

const HeaderCity = styled.div`
  text-align:center;
  text-transform
`
const HeaderTop = styled.div`
  font-size: 24px; /* set desired font size */
  text-shadow: 1px 1px 2px rgba(0, 0, 0, 0.1); /* set desired drop shadow */
  line-height: 1.2; /* set desired line height */
  letter-spacing: 1px; /* set desired letter spacing */
`
const HeaderBottom = styled.div`
color: rgba(128, 128, 128, 0.7);
`;

const BackButton = styled.button`
  position: absolute;
  top: 10px; /* Adjust top value to desired position */
  left: 10px; /* Adjust left value to desired position */
  background-color: #ccc;
  padding: 5px 20px 0px 20px;
  border: none;
  border-radius: 5px;
  cursor: pointer;
  font-size:20px;
  color:#ffffff;
`;

const AddGrubButton = styled.div`
  box-shadow: 0 5px 15px rgba(0, 0, 0, 0.2); 
  text-align:center;
  border-radius: 15px;
  padding: 20px;
  background:#0C86D6;
  margin-top:10px;
`
const GrubContainer = styled.div`
  box-shadow: 0 5px 15px rgba(0, 0, 0, 0.2);
  border-radius: 15px;
  padding: 20px;
  margin-top: 10px;
  margin-bottom: 10px;
  transition: all 0.3s ease;
  transform-origin: top center;
  cursor: pointer;
`;


export default Grubs;